### ISSUE TITLE
Create Comprehensive User Manual for Apache NiFi

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/oms-documentation#240]
**Overview:**
Initiating the development of a user manual for Apache NiFi to enhance user experience and provide comprehensive guidance on setup, configuration, and advanced usage.

**Scope:**
- Cover fundamental concepts.
- Provide step-by-step guides.
- Include troubleshooting tips and best practices.

**Benefits:**
Empower users, reduce support requests, and foster a positive user experience. Contributors are invited to collaborate on this initiative.

**How to Contribute:**
Review existing documentation, gather insights, and submit drafts for feedback.

**Comment by Amir-HC** [comment]
Added Document
