### ISSUE TITLE
Request for Documentation: "Search Admin" 

### ISSUE THREAD

**Issue by sinhaaditya2** [hotwax/oms-documentation#242]
### Description:
The 'Search Admin' functionality lacks comprehensive documentation, leading to a lack of clarity and potential challenges for users attempting to navigate and utilize this feature. To improve user experience and facilitate better understanding, it is essential to create thorough documentation for the 'Search Admin' module.

### Details:
- **Introduction:**
  - Overview of 'Search Admin'
  - Importance and benefits
  
- **Getting Started:**
  - Accessing 'Search Admin'

- **Configuration:**
  - Detailed explanation of configurable settings
  - Step-by-step guide for customization

- **Functionality:**
  - In-depth explanation of each feature within 'Search Admin'
  - Use cases and practical examples

- **Troubleshooting:**
  - Common issues and their resolutions
  - Troubleshooting guide

### Additional Information:
Any additional information or context that may assist in the documentation process.

**Note:**
Collaboration and feedback from the community are encouraged to enhance the quality and comprehensiveness of the documentation.

**Comment by Amir-HC** [comment]
Added Documentation
